name: Documentation Update

on:
  push:
	branches: [ $default-branch ]
  pull_request:
	branches: [ $default-branch ]

jobs:
  automerge:

	runs-on: ubuntu-latest

	steps:
	  - name: automerge
		uses: "pascalgn/automerge-action@f81beb99aef41bb55ad072857d43073fba833a98"
		env:
		  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  build:

	runs-on: ubuntu-latest

	strategy:
	  matrix:
		node-version: [10.x, 12.x, 14.x]

	steps:
	- uses: actions/checkout@v2
	- name: Use Node.js ${{ matrix.node-version }}
	  uses: actions/setup-node@v1
	  with:
		node-version: ${{ matrix.node-version }}
	- run: npm run doc
  
